import 'dart:convert';
import 'dart:io';

/// Reconstructs the visible text of a PDF generated by the `pdf` package by
/// inflating its FlateDecode-compressed content streams and extracting
/// Tj/TJ text-showing operator strings.
///
/// NOTE: This is coupled to the `pdf` package's internal PDF-writer output
/// format (compression + operator choice), not a public API. Verified
/// working against pdf ^3.12.0's actual output (13-RESEARCH.md Pattern 3).
/// If a future `pdf` upgrade changes compression defaults or font/kerning
/// handling (e.g. switches to per-glyph TJ arrays), re-verify this helper.
String extractPdfText(File pdfFile) {
  final bytes = pdfFile.readAsBytesSync();
  final text = latin1.decode(bytes, allowInvalid: true);
  final streamRe = RegExp(
    r'<<[^>]*?/Filter\s*/FlateDecode[^>]*?>>\s*stream\r?\n',
    dotAll: true,
  );
  final buffer = StringBuffer();
  for (final m in streamRe.allMatches(text)) {
    final start = m.end;
    final end = text.indexOf('endstream', start);
    if (end == -1) continue;
    var rawEnd = end;
    while (rawEnd > start &&
        (bytes[rawEnd - 1] == 0x0a || bytes[rawEnd - 1] == 0x0d)) {
      rawEnd--;
    }
    List<int> inflated;
    try {
      inflated = zlib.decode(bytes.sublist(start, rawEnd));
    } catch (_) {
      continue; // not every stream is FlateDecode text — skip safely
    }
    final content = latin1.decode(inflated);
    for (final t in RegExp(
      r'\(((?:[^()\\]|\\.)*)\)\s*Tj',
    ).allMatches(content)) {
      buffer
        ..write(_unescape(t.group(1)!))
        ..write(' ');
    }
    for (final arr in RegExp(r'\[((?:[^\[\]])*)\]\s*TJ').allMatches(content)) {
      for (final s in RegExp(
        r'\(((?:[^()\\]|\\.)*)\)',
      ).allMatches(arr.group(1)!)) {
        buffer.write(_unescape(s.group(1)!));
      }
      buffer.write(' ');
    }
  }
  return buffer.toString();
}

String _unescape(String s) =>
    s.replaceAll(r'\(', '(').replaceAll(r'\)', ')').replaceAll(r'\\', r'\');
